// src/features/checklist/checklistSlice.js

import { createSlice } from '@reduxjs/toolkit';

const initialState = {
  items: [
    { 
      id: 1, 
      text: "Pre-startup inspection completed", 
      checked: true, 
      category: "Startup",
      description: "Complete visual and physical inspection of all turbine components before startup",
      details: "Walk around inspection checking for loose components, leaks, foreign objects, and structural integrity",
      acceptanceCriteria: "No visible damage, leaks, or foreign objects detected. All access panels secured.",
      procedure: "1. Inspect casing for cracks or deformation\n2. Check all mounting bolts for proper torque\n3. Verify no foreign objects in inlet/outlet\n4. Inspect piping for leaks or damage\n5. Confirm all safety guards in place",
      reference: "OEM Manual Section 4.1 - Pre-startup Inspection",
      frequency: "Before each startup after >24hr shutdown",
      criticalNote: "Failure to complete inspection may result in catastrophic damage"
    },
    { 
      id: 2, 
      text: "Oil levels verified", 
      checked: true, 
      category: "Lubrication",
      description: "Verify lubrication oil levels are within acceptable operating range",
      details: "Check oil reservoir sight glass and measure oil level using dipstick method",
      acceptanceCriteria: "Oil level between MIN and MAX markers. Oil appearance clean without metal particles or discoloration.",
      procedure: "1. Ensure turbine is shutdown and cooled\n2. Check main oil reservoir sight glass\n3. Verify bearing housing oil levels\n4. Check oil quality (color, viscosity, contamination)\n5. Document oil level and condition",
      reference: "Lubrication System Manual Section 3.2",
      normalRange: "Oil level: 75-85% of reservoir capacity",
      frequency: "Daily before startup",
      criticalNote: "Low oil levels can cause bearing failure within minutes of operation"
    },
    { 
      id: 3, 
      text: "Pressure sensors calibrated", 
      checked: false, 
      category: "Sensors",
      description: "Calibrate inlet and outlet pressure transmitters against reference standards",
      details: "Multi-point calibration check using precision pressure gauges at 0%, 25%, 50%, 75%, and 100% span",
      acceptanceCriteria: "Sensor accuracy within ±0.5% of reading across full range. Zero and span drift <0.1% per month.",
      procedure: "1. Isolate sensor from process\n2. Connect reference standard\n3. Apply 5-point calibration pressures\n4. Record readings and compare to standard\n5. Adjust zero and span if needed\n6. Document calibration results",
      reference: "Instrumentation Manual Section 5.3 - Pressure Transmitter Calibration",
      equipment: "Fluke 718 Pressure Calibrator or equivalent",
      normalRange: "Pin: 1-4 bar, Pout: 12-18 bar (IGT-12MW)",
      frequency: "Monthly or after any maintenance",
      criticalNote: "Inaccurate pressure readings can lead to surge conditions or compressor damage"
    },
    { 
      id: 4, 
      text: "Temperature probes tested", 
      checked: true, 
      category: "Sensors",
      description: "Verify accuracy of RTD and thermocouple temperature sensors",
      details: "Test exhaust gas, bearing, and oil temperature sensors using calibrated temperature source",
      acceptanceCriteria: "Temperature accuracy within ±2°C for RTDs, ±3°C for thermocouples. Response time <5 seconds.",
      procedure: "1. Remove sensor from process\n2. Use temperature calibration bath or dry block\n3. Test at 3 points: ambient, 100°C, 400°C\n4. Record response time and accuracy\n5. Replace if outside tolerance\n6. Document test results",
      reference: "Instrumentation Manual Section 5.4 - Temperature Sensor Testing",
      equipment: "Fluke 9102S Dry-Well Calibrator",
      normalRange: "Texh: 450-550°C, Tbearing: 60-90°C, Toil: 40-65°C",
      frequency: "Quarterly",
      criticalNote: "Failed temperature sensors can mask overheat conditions leading to thermal damage"
    },
    { 
      id: 5, 
      text: "Vibration monitoring active", 
      checked: false, 
      category: "Monitoring",
      description: "Confirm vibration monitoring system is operational and collecting data",
      details: "Verify all accelerometers are functioning and data is being logged to monitoring system",
      acceptanceCriteria: "All vibration sensors reading <7.1 mm/s RMS during operation. Data acquisition rate ≥10kHz. No sensor faults.",
      procedure: "1. Check sensor connections and cables\n2. Verify data acquisition system status\n3. Perform bump test on each sensor\n4. Review baseline vibration spectrum\n5. Set alarm thresholds per ISO 10816\n6. Enable real-time monitoring",
      reference: "Vibration Monitoring Manual Section 2.1, ISO 10816-3",
      normalRange: "Axial: 2-4 mm/s RMS, Radial: 3-5 mm/s RMS (normal operation)",
      alarmLimits: "Alert: 7.1 mm/s, Alarm: 11.0 mm/s, Trip: 18.0 mm/s (per ISO 10816-3 Zone C/D)",
      frequency: "Continuous monitoring during operation",
      criticalNote: "Vibration monitoring is primary indicator of bearing wear, imbalance, and misalignment"
    },
    { 
      id: 6, 
      text: "Emergency shutdown tested", 
      checked: true, 
      category: "Safety",
      description: "Test emergency shutdown (ESD) system functionality",
      details: "Verify ESD push buttons, remote triggers, and automatic trip conditions function correctly",
      acceptanceCriteria: "ESD activation closes fuel valve in <0.5 seconds. All interlocks respond correctly. Reset function works properly.",
      procedure: "1. Notify all personnel of ESD test\n2. Test manual ESD push buttons (all locations)\n3. Test remote shutdown signal\n4. Verify fuel valve closure time\n5. Test automatic trips (overspeed, high temp, low oil pressure)\n6. Test ESD reset and restart permissives\n7. Document all test results",
      reference: "Safety System Manual Section 7.1 - ESD Testing, IEC 61508",
      testFrequency: "Monthly for manual buttons, Quarterly for full system",
      frequency: "Monthly",
      criticalNote: "ESD system must be functional before every startup. SIL-2 rated system required per safety analysis."
    },
    { 
      id: 7, 
      text: "Inlet filters inspected", 
      checked: false, 
      category: "Maintenance",
      description: "Inspect and clean inlet air filters to ensure adequate airflow",
      details: "Check filter differential pressure and physical condition. Clean or replace as needed.",
      acceptanceCriteria: "Differential pressure across filters <50 mbar. No tears, holes, or bypass. Filter media clean.",
      procedure: "1. Measure and record inlet filter ΔP\n2. Perform visual inspection for damage\n3. Remove and clean/replace filters if ΔP >50 mbar\n4. Check filter housing seals\n5. Verify filter installation and seating\n6. Record filter condition and actions taken",
      reference: "Maintenance Manual Section 6.2 - Air Intake System",
      normalRange: "Clean filter ΔP: 5-20 mbar, Replace at: >50 mbar or visible contamination",
      replacementCriteria: "Replace filters every 2000 operating hours or when ΔP >50 mbar",
      frequency: "Weekly inspection, Replace per schedule or condition",
      criticalNote: "Dirty filters reduce mass flow, increase compressor inlet temp, and decrease efficiency by 2-5%"
    },
    { 
      id: 8, 
      text: "Outlet valves operational", 
      checked: true, 
      category: "Operations",
      description: "Verify compressor outlet control valves operate smoothly throughout full range",
      details: "Test anti-surge valve, bypass valve, and discharge isolation valves for proper operation",
      acceptanceCriteria: "Valves respond to control signals within 1 second. Travel time 0-100%: <5 seconds. No sticking or hunting.",
      procedure: "1. Test anti-surge valve in manual mode (0-100%)\n2. Check valve position feedback accuracy\n3. Test valve response time\n4. Verify pneumatic/hydraulic supply pressure\n5. Check for air/oil leaks at actuator\n6. Test bypass valve operation\n7. Perform valve signature analysis",
      reference: "Control Valve Manual Section 4.3 - Valve Testing",
      normalRange: "Anti-surge valve: Normally <10% open, Supply pressure: 6 bar (pneumatic)",
      frequency: "Monthly functional test, Quarterly stroke test",
      criticalNote: "Anti-surge valve failure can result in compressor surge causing severe damage in seconds"
    },
    { 
      id: 9, 
      text: "Fuel system pressure check", 
      checked: true, 
      category: "Startup",
      description: "Verify fuel gas supply pressure and quality meet specifications",
      details: "Check fuel gas pressure, temperature, and perform leak test on fuel system",
      acceptanceCriteria: "Fuel pressure: 25-30 bar. Temperature: 15-40°C. No leaks detected. Gas quality per specification.",
      procedure: "1. Check fuel supply header pressure\n2. Verify fuel gas temperature\n3. Inspect fuel filter differential pressure\n4. Perform soap bubble leak test on connections\n5. Check fuel gas composition (if analyzer available)\n6. Verify fuel valve actuator pressure\n7. Test fuel valve closure",
      reference: "Fuel System Manual Section 3.1, NFPA 54",
      normalRange: "Supply pressure: 27±2 bar, Filter ΔP: <0.5 bar, Methane content: >85%",
      leakTest: "Zero leak tolerance - use gas detector <500 ppm LEL",
      frequency: "Before each startup",
      criticalNote: "Fuel leaks present explosion hazard. Low pressure causes flame instability and turbine trip."
    },
    { 
      id: 10, 
      text: "Cooling water flow verified", 
      checked: true, 
      category: "Lubrication",
      description: "Verify cooling water system flow rate and temperature",
      details: "Check oil cooler water flow, inlet/outlet temperatures, and system pressure",
      acceptanceCriteria: "Water flow: ≥50 L/min. Inlet temp: 15-30°C. Outlet temp: <45°C. Pressure: 3-5 bar.",
      procedure: "1. Check cooling water supply pressure\n2. Measure water flow rate (flow meter)\n3. Record inlet and outlet temperatures\n4. Inspect for water leaks\n5. Check oil cooler performance (oil temp drop)\n6. Verify automatic makeup water system\n7. Test low flow alarm",
      reference: "Cooling System Manual Section 2.4",
      normalRange: "Flow: 50-80 L/min, ΔT: 10-15°C across oil cooler",
      alarmLimits: "Low flow: <40 L/min, High temp: >50°C outlet",
      frequency: "Daily",
      criticalNote: "Cooling water loss can cause oil overheat leading to bearing failure within 10-15 minutes"
    },
    { 
      id: 11, 
      text: "Flow meters calibrated", 
      checked: false, 
      category: "Sensors",
      description: "Calibrate mass flow and volumetric flow measurement devices",
      details: "Verify accuracy of inlet air flow, fuel flow, and discharge flow meters",
      acceptanceCriteria: "Flow measurement accuracy within ±2% of reading. Zero cutoff stable. Density compensation active (if mass flow).",
      procedure: "1. Record current flow meter readings\n2. Compare to reference flow (portable ultrasonic or pitot tube)\n3. Check zero flow condition\n4. Verify density compensation (for mass flow meters)\n5. Adjust meter factor if needed\n6. Check for fouling or deposits\n7. Document calibration results",
      reference: "Flow Measurement Manual Section 4.2, ISO 5167",
      equipment: "Portable ultrasonic flow meter or Pitot traverse kit",
      normalRange: "Air flow: 15-20 kg/s, Fuel flow: 0.3-0.5 kg/s (at rated load)",
      frequency: "Semi-annually or after process changes",
      criticalNote: "Inaccurate flow measurement affects performance calculations and surge detection"
    },
    { 
      id: 12, 
      text: "Vibration sensors tested", 
      checked: true, 
      category: "Sensors",
      description: "Test accelerometer and proximity probe functionality",
      details: "Perform bump test and electrical continuity check on all vibration sensors",
      acceptanceCriteria: "Bump test shows clear resonant peak >20 g. Sensor impedance: 5-25 ohms. Cable capacitance: <3000 pF.",
      procedure: "1. Disconnect sensor from monitoring system\n2. Perform electrical continuity test\n3. Conduct bump test with hammer\n4. Analyze frequency response (should show sensor resonance)\n5. Check cable condition and shielding\n6. Verify sensor mounting torque\n7. Reconnect and verify signal quality",
      reference: "Vibration Manual Section 3.3, ISO 10816",
      equipment: "Accelerometer bump tester or portable FFT analyzer",
      normalRange: "Accelerometer sensitivity: 100 mV/g ±10%",
      frequency: "Annually or after any sensor-related maintenance",
      criticalNote: "Failed vibration sensors eliminate early warning of mechanical problems"
    },
    { 
      id: 13, 
      text: "Fire suppression system active", 
      checked: true, 
      category: "Safety",
      description: "Test fire detection and suppression system readiness",
      details: "Verify fire detectors, alarms, and automatic suppression system are operational",
      acceptanceCriteria: "All detectors responsive. CO2/FM200 bottles at full charge (>95%). Manual activation works. Auto-trigger tested.",
      procedure: "1. Test smoke/heat detectors (test button or smoke stick)\n2. Verify alarm annunciation in control room\n3. Check suppression agent bottle pressure gauge\n4. Test manual release stations\n5. Verify electrical continuity to actuators\n6. Check nozzle orientation and condition\n7. Test pre-discharge alarm (without release)\n8. Document system status",
      reference: "Fire Protection Manual Section 5.1, NFPA 72 & NFPA 2001",
      normalRange: "CO2 bottles: >95% charge, FM-200: >90% charge",
      testFrequency: "Monthly detector test, Quarterly full system test (no discharge)",
      frequency: "Monthly",
      criticalNote: "Fire suppression must be fully operational. Turbine fires can cause total loss in <2 minutes."
    },
    { 
      id: 14, 
      text: "Compressor blades inspected", 
      checked: false, 
      category: "Maintenance",
      description: "Borescope inspection of compressor rotor and stator blades",
      details: "Visual inspection for blade damage, erosion, fouling, and foreign object damage (FOD)",
      acceptanceCriteria: "No cracks, chips >3mm, or blade tip rubs. Minimal erosion (<0.5mm). No FOD. Blade coating intact.",
      procedure: "1. Shutdown and lockout turbine\n2. Allow cooling to <50°C\n3. Remove borescope access port plugs\n4. Insert borescope and inspect each stage\n5. Document any damage with photos\n6. Check for uniform fouling patterns\n7. Note any tip rubs or clearance issues\n8. Reinstall port plugs with new seals",
      reference: "Inspection Manual Section 8.2, OEM Blade Acceptance Criteria",
      equipment: "Industrial borescope with HD camera and articulation",
      inspectionPoints: "Inlet guide vanes, Stages 1-8 rotor blades, Stages 1-8 stator vanes",
      frequency: "Every 2000 operating hours or annually",
      criticalNote: "Blade damage can lead to compressor failure. FOD must be removed immediately."
    },
    { 
      id: 15, 
      text: "Control valves operational", 
      checked: true, 
      category: "Operations",
      description: "Test inlet guide vanes (IGV) and variable stator vanes (VSV) operation",
      details: "Verify IGV/VSV positioning system responds correctly to control signals",
      acceptanceCriteria: "IGV/VSV travel 0-100% in <8 seconds. Position accuracy ±1%. No mechanical binding or excessive noise.",
      procedure: "1. Switch to manual control mode\n2. Command IGV to 0% position\n3. Verify position feedback and timing\n4. Command IGV to 100% position\n5. Check for smooth motion (no jumps)\n6. Test intermediate positions (25%, 50%, 75%)\n7. Verify actuator supply pressure\n8. Listen for abnormal sounds\n9. Return to automatic control",
      reference: "Control System Manual Section 6.4 - Variable Geometry",
      normalRange: "IGV position at rated load: 75-85% open, Actuator pressure: 6-8 bar",
      frequency: "Weekly",
      criticalNote: "Stuck IGV can cause surge or efficiency loss. Failed IGV actuator requires immediate shutdown."
    },
    { 
      id: 16, 
      text: "Electrical connections verified", 
      checked: true, 
      category: "Startup",
      description: "Inspect electrical power supply and control system connections",
      details: "Check main power connections, control voltage, grounding, and cable terminations",
      acceptanceCriteria: "Main power: 3-phase 400V±10%, 50Hz±2%. Control voltage: 24VDC±5%. Ground resistance: <1 ohm. No loose connections.",
      procedure: "1. Measure main power supply voltage (L1-L2-L3)\n2. Check voltage balance (<2% deviation)\n3. Verify control power supply (24VDC)\n4. Test UPS battery backup (load test)\n5. Check ground continuity and resistance\n6. Inspect cable glands and terminations\n7. Thermal scan of electrical panels (if available)\n8. Verify no loose connections",
      reference: "Electrical System Manual Section 2.1, IEC 60204-1",
      equipment: "Multimeter, Megger, Ground resistance tester, Thermal imager",
      normalRange: "Main power: 380-420V, Phase balance: ±2%, Ground: <1 ohm",
      frequency: "Monthly",
      criticalNote: "Electrical faults can cause control system failure and unsafe turbine operation"
    },
    { 
      id: 17, 
      text: "Bearing temperature normal", 
      checked: true, 
      category: "Monitoring",
      description: "Monitor bearing temperatures are within acceptable operating range",
      details: "Verify all journal and thrust bearing temperatures during operation",
      acceptanceCriteria: "Bearing temps: 60-90°C during normal operation. Alarm: >95°C. Trip: >105°C. Temperature rise <40°C above oil inlet.",
      procedure: "1. Record bearing temperatures from DCS\n2. Compare to baseline readings\n3. Check temperature distribution (front/rear bearings)\n4. Calculate bearing metal temperature rise\n5. Trend temperatures over last 24 hours\n6. Verify oil flow to each bearing\n7. Check for hot spots with thermal scanner\n8. Document any anomalies",
      reference: "Bearing System Manual Section 4.2, API 617",
      normalRange: "Journal bearings: 65-85°C, Thrust bearing: 70-90°C, Oil inlet: 45-55°C",
      alarmLimits: "Alert: 95°C, Alarm: 100°C, Trip: 105°C",
      frequency: "Continuous monitoring during operation",
      criticalNote: "Bearing overheating >105°C can cause Babbitt failure and catastrophic damage within minutes"
    },
    { 
      id: 18, 
      text: "Exhaust system clear", 
      checked: true, 
      category: "Maintenance",
      description: "Inspect exhaust duct and silencer for blockages and structural integrity",
      details: "Visual inspection of exhaust path, silencer internals, and support structures",
      acceptanceCriteria: "No obstructions in exhaust flow path. Silencer baffles intact. No excessive vibration. Exhaust temperature uniform.",
      procedure: "1. Inspect exhaust duct exterior for hot spots\n2. Check expansion joints for damage/leaks\n3. Verify exhaust stack support integrity\n4. Inspect silencer inlet for blockage\n5. Check for carbon buildup or deposits\n6. Verify drain traps are clear\n7. Measure exhaust back pressure\n8. Listen for unusual flow noise",
      reference: "Exhaust System Manual Section 7.3",
      normalRange: "Exhaust back pressure: <50 mbar, Temperature uniformity: ±20°C across stack",
      frequency: "Monthly visual inspection, Annual internal inspection",
      criticalNote: "Exhaust blockage increases back pressure, reduces power output, and can cause high exhaust temperature trip"
    },
  ],
};

const checklistSlice = createSlice({
  name: 'checklist',
  initialState,
  reducers: {
    toggleChecklistItem: (state, action) => {
      const item = state.items.find(item => item.id === action.payload);
      if (item) {
        item.checked = !item.checked;
      }
    },
  },
});

export const { toggleChecklistItem } = checklistSlice.actions;
export default checklistSlice.reducer;